openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
tags:
  - name: samples
    description: sample resource api list
paths:
  /samples:
    get:
      summary: get sample resources
      operationId: getSamples
      description: find samples resources
      tags:
        - samples
      parameters:
        - name: sort
          in: query
          description: 정렬 기준
          allowEmptyValue: true
          required: false
          schema:
            type: integer
            default: 1
        - name: filter
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: integer
            default: 1
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SamplesResponse'
        400:
          description: Invalid request data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                bad request in invalid request data:
                  value:
                    code: SM001
                    message: invalid request data
                find other users resources:
                  value:
                    code: SM002
                    message: permission denied
        404:
          description: resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                sample not found:
                  value:
                    code: SM003
                    message: sample not found
                sample owner not found:
                  value:
                    code: SM004
                    message: sample owner not found
    post:
      tags:
        - samples
      description: create sample resource
      operationId: createSample
      summary: create sample
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSampleRequest'
      responses:
        200:
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SamplesResponse'
        400:
          description: invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalid request data:
                  value:
                    code: CM001
                    message: Invalid request data
        409:
          description: duplicate name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: SM003
                message: duplicate name
components:
  schemas:
    CreateSampleRequest:
      type: object
      properties:
        name:
          type: string
          description: "sample name"
          nullable: false
    SamplesResponse:
      type: object
      properties:
        name:
          type: string
          description: "sample resource name"
          nullable: false
        createdAt:
          type: string
          description: "sample resource created date"
          nullable: false
          format: yyyy-MM-ddThh:mm:ssZ
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: custom error code
        message:
          type: string
          description: error message